# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Office of Jason James | Designer
email: hello@jasonjam.es
description: > # this means to ignore newlines until "baseurl:"
  The portfolio and blog of Jason James – Oakland-based designer of companies, teams, brands, and products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jasonjam.es" # the base hostname & protocol for your site
twitter_username: jas0njames
github_username:  jas0njames

# Build settings
markdown: kramdown
